# Generated by Django 4.2.1 on 2023-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'dependencias',
                'db_table': 'Dependencia',
            },
        ),
    ]
