# Generated by Django 4.2.1 on 2023-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackendPantallaPrincipalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'ordering': ['nombre'], 'verbose_name': 'Dependencia', 'verbose_name_plural': 'dependencias'},
        ),
        migrations.AddField(
            model_name='dependencia',
            name='url',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
